name: test-vac

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get install libasound2-dev pulseaudio alsa-utils

      - name: test dummy audiocore
        run: |
          modinfo soundcore

      # - name: Create virtual audio cable
      #   run: |
      #     pacmd load-module module-null-sink sink_name=Virtual_Sink sink_properties=device.description=Virtual_Sink

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7

      - name: Install npm dependencies
        run: pnpm install

      - name: Dev
        run: pnpm dev
